### ISSUE TITLE
Possível bug

### ISSUE THREAD

**Issue by BielCellos** [Monaco-a-Knox/amantesamentes#1]
O início do jogo fica em português, porém após começarem os dialógos ele fica em inglês novamente (versão da steam)

![{F9335AAC-5F4F-4B84-9B03-AAC63375440A}](https://github.com/user-attachments/assets/ca08d1df-3877-4a65-adf7-87ab8346701e)
![{F9335AAC-5F4F-4B84-9B03-AAC63375440A}](https://github.com/user-attachments/assets/4715a7f3-6f31-4f72-8eee-474e06e4b2e5)

**Comment by Monaco-a-Knox** [comment]
Não é bug.

Se você abriu o jogo alguma vez antes de aplicar o patch, ele cria um save automático e o texto antigo fica armazenado em cache até o fim do capítulo, iniciar novo jogo ou deletar o save. 

(Mudar o nome do jogo na janela, editando o arquivo .ini, também resolve porque cria um novo save) 

Dito isso, como pretendo lançar a versão final em 4 dias, não vale muito a pena ler a versão de testes (exceto se queira testar e reportar erros)

**Comment by BielCellos** [comment]
Entendi, obrigado pela resposta.

**Comment by Monaco-a-Knox** [comment]
Atualização: realmente parece não estar mais funcionando na steam.

Recomendo que adquira a versão da mangagamer até eu pense em uma solução,

**Comment by Monaco-a-Knox** [comment]
@BielCellos 

Boa noite.

Fiz uma atualização e agora deve funcionar com a versão Steam.

Ocorre que DX e Steam estão puxando arquivos com nomes diferentes. Se não funcionar agora, não há mais o que eu possa fazer.

**Comment by BielCellos** [comment]
Nesse caso vai ser só colocar os arquivos na pasta do jogo? Ou eu preciso
deletar o save automático?

Em qua., 25 de dez. de 2024, 21:58, Monaco-a-Knox ***@***.***>
escreveu:

**Comment by Monaco-a-Knox** [comment]
Só baixar a v1.0.1 e colocar os arquivos na pasta.
Se não estiver traduzido, delete o save.

**Comment by BielCellos** [comment]
E existe alguma forma de aumentar a fonte de texto?

**Comment by Monaco-a-Knox** [comment]
Pode editar o arquivo "malie.ini" no bloco de notas e alterar o valor da fonte, mas isso fará com que diversas linhas ultrapassem o limite da caixa de texto.

**Comment by BielCellos** [comment]
Como eu posso deletar o cache dos textos antigos?

**Comment by Monaco-a-Knox** [comment]
> Se você abriu o jogo alguma vez antes de aplicar o patch, ele cria um save automático e o texto antigo fica armazenado em cache até o fim do capítulo, iniciar novo jogo ou deletar o save. 
> 
> 
> 
> (Mudar o nome do jogo na janela, editando o arquivo .ini, também resolve porque cria um novo save)

**Comment by BielCellos** [comment]
Eu edito o nome do arquivo .ini?

**Comment by Monaco-a-Knox** [comment]
Linha 9 do malie.ini

Só mudar o nome do jogo.
