### ISSUE TITLE
Link quebrado no site.

### ISSUE THREAD

**Issue by LotteBestGirl** [Monaco-a-Knox/amantesamentes#2]
https://knox.fansub.com.br/gestapo/
Esse redireciona para "Dia-da-ira" ao invés de "amantesamentes", achei que o projeto tinha sido excluído por esse erro. Uma atualização seria bem vinda.

**Comment by Monaco-a-Knox** [comment]
Bom dia, amigo.

Eu precisei criar um novo por causa de um erro do GitHub Desktop, que afirmava que o repositório estava vazio.

Infelizmente, não posso arrumar agora. Antes de bloquear o acesso estrangeiro ao site, havia muitas tentativas de invasão diariamente, então coloquei uma trava de 900 horas após a primeira tentativa... acontece que eu caí nessa trava e meu IP está bloqueado até o fim de janeiro.

Vou falar com o responsável pelo servidor e ver se ele consegue atualizar o link.
